name: mlflow-tracker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: start mlflow server
        run: |
          nohup mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 127.0.0.1 --port 5000 & sleep 10  # Give the server some time to start


      - name: Run scri[t]
        env:
          ACCESS_KEY: ${{ secrets.SECRET_KEY }}
          SECRET_KEY: ${{ secrets.API_KEY }}
          MLFLOW_TRACKING_URI: "http://127.0.0.1:5000"

        run: |
          python train_iris.py
